# Generated by Django 5.0.6 on 2025-04-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globeapp', '0003_language_smpost_brands_smpost_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='smpost',
            old_name='brands',
            new_name='brand',
        ),
    ]
