# Generated by Django 5.0.6 on 2025-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeapp', '0004_rename_brands_brand_rename_brands_smpost_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpost',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
