# Generated by Django 5.0.6 on 2025-04-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeapp', '0005_smpost_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
