# Generated by Django 5.0.6 on 2025-04-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeapp', '0006_smplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpost',
            name='post_author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
