# Generated by Django 5.0.6 on 2025-04-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeapp', '0008_smpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smpost',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_posts', to='globeapp.location'),
        ),
    ]
