# Generated by Django 5.0.6 on 2025-04-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeapp', '0009_alter_smpost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smpost',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_posts', to='globeapp.brand'),
        ),
        migrations.AlterField(
            model_name='smpost',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_posts', to='globeapp.language'),
        ),
    ]
