# Generated by Django 5.0.6 on 2025-04-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globeapp', '0010_alter_smpost_brand_alter_smpost_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='smpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
